# local access only
server.address=127.0.0.1

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.paths-to-match=/api/**

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.persist-authorization=false
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

# Disable external specification validation
springdoc.swagger-ui.validator-url=