ALTER TABLE audit_events
DROP
CONSTRAINT ck_audit_events_action;

ALTER TABLE audit_events
    ADD CONSTRAINT ck_audit_events_action
        CHECK (
    action IN (
    'OBSERVATION_CREATE',
    'OBSERVATION_LIST',
    'OBSERVATION_READ',
    'TIMELINE_READ',
    'AUDIT_EVENTS_LIST',
    'REPORT_GENERATE',
    'REPORT_PDF_EXPORT',
    'USER_CREATE',
    'USER_STATUS_UPDATE',
    'CONSENT_CREATE',
    'CONSENT_REVOKE',
    'STUDENT_CREATE',
    'STUDENT_UPDATE',
    'STUDENT_STATUS_UPDATE',
    'GUARDIAN_CREATE',
    'GUARDIAN_UPDATE',
    'GUARDIAN_STATUS_UPDATE',
    'STUDENT_GUARDIAN_LINK_CREATE',
    'STUDENT_GUARDIAN_LINK_UPDATE',
    'STUDENT_GUARDIAN_LINK_DELETE',
    'CARE_TEAM_LINK_CREATE',
    'CARE_TEAM_LINK_END'
    )
    );